<?php

namespace AppBundle\Repository;

/**
 * PlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends \Doctrine\ORM\EntityRepository {


    /**
     * Get all men players
     * @return \Doctrine\ORM\Query
     */
    public function getMen() {
        $qb = $this->createQueryBuilder('p');

        $qb->where('p.female = false')
            ->orderBy('p.lastname', 'ASC');

        return $qb->getQuery();
    }

    /**
     * Get all women players
     * @return \Doctrine\ORM\Query
     */
    public function getWomen() {
        $qb = $this->createQueryBuilder('p');

        $qb->where('p.female = true')
            ->orderBy('p.lastname', 'ASC');

        return $qb->getQuery();
    }

    /**
     * Get players with teams information
     * @return \Doctrine\ORM\Query
     */
    public function getPlayersTeams() {
        $qb = $this->createQueryBuilder('p');

        $qb->addSelect('teams')
            ->leftJoin('p.teams','teams');

        return $qb->getQuery();
    }

    /**
     * Get a player with his id
     * @param $id
     * @return \Doctrine\ORM\Query
     */
    public function getPlayerById($id) {
        $qb = $this->createQueryBuilder('p');

        $qb->where('p.id = ?1')
            ->setParameter(1, $id);

        return $qb->getQuery();
    }

}
