<?php

namespace AppBundle\Repository;

/**
 * RefereeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefereeRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllReferee()
    {
        $query = $this->_em->createQuery(
            'SELECT r
    		FROM AppBundle:Referee r
    		ORDER BY r.lastname ASC' );

        return $query->getResult();

    }
}
