<?php

namespace AppBundle\Repository;

/**
 * RefereeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefereeRepository extends \Doctrine\ORM\EntityRepository
{
}
