<?php

namespace AppBundle\Repository;

/**
 * TennisMatchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TennisMatchRepository extends \Doctrine\ORM\EntityRepository
{
}
