<?php

namespace AppBundle\Repository;

/**
 * TournamentTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TournamentTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
